# Generated by Django 4.2.26 on 2025-11-25 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('current_occupation', models.CharField(blank=True, max_length=100)),
                ('marriage_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parity', models.CharField(blank=True, max_length=50)),
                ('new_partner_pregnancy', models.BooleanField(null=True)),
                ('child_spacing_over_10_years', models.BooleanField(null=True)),
                ('ivf_pregnancy', models.BooleanField(null=True)),
                ('multiple_pregnancy', models.BooleanField(null=True)),
                ('smoker', models.BooleanField(null=True)),
                ('planned_pregnancy', models.BooleanField(null=True)),
                ('family_history_pe', models.BooleanField(null=True)),
                ('personal_history_pe', models.BooleanField(null=True)),
                ('chronic_hypertension', models.BooleanField(null=True)),
                ('diabetes_mellitus', models.BooleanField(null=True)),
                ('kidney_disease', models.BooleanField(null=True)),
                ('autoimmune_disease', models.BooleanField(null=True)),
                ('aps_history', models.BooleanField(null=True)),
                ('pre_pregnancy_weight', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('lila_cm', models.FloatField(blank=True, null=True)),
                ('blood_pressure_td1', models.FloatField(blank=True, null=True)),
                ('map_mmhg', models.FloatField(blank=True, null=True)),
                ('hemoglobin', models.FloatField(blank=True, null=True)),
                ('family_history_hypertension', models.BooleanField(null=True)),
                ('family_history_kidney', models.BooleanField(null=True)),
                ('family_history_heart', models.BooleanField(null=True)),
                ('result', models.CharField(blank=True, max_length=50)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
