# Generated by Django 5.2.9 on 2025-12-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_alter_bloodpressure_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningsubmission',
            name='blood_pressure_td1',
        ),
        migrations.AddField(
            model_name='screeningsubmission',
            name='diastolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screeningsubmission',
            name='district_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='screeningsubmission',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='screeningsubmission',
            name='systolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
